// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'active-title': string;
  'activePeriod': string;
  'circle': string;
  'controlSwiper': string;
  'controls': string;
  'endYear': string;
  'eventDesc': string;
  'eventYear': string;
  'historical-container': string;
  'historical-gradient': string;
  'historical-title': string;
  'horizontalLine': string;
  'indexDisplay': string;
  'mobileHorizLine': string;
  'mobileTitle': string;
  'navButton': string;
  'navButtons': string;
  'periodDot': string;
  'periodPagination': string;
  'point-circle': string;
  'point-text': string;
  'startYear': string;
  'swiperContainer': string;
  'swiperNavButton': string;
  'swiperNavButtonNext': string;
  'swiperNavButtonPrev': string;
  'swiperSlide': string;
  'timelineContainer': string;
  'verticalLineLeft': string;
  'verticalLineMiddle': string;
  'verticalLineRight': string;
  'visualWrapper': string;
  'yearDisplay': string;
}
export const cssExports: CssExports;
export default cssExports;
